name: Java CI with OpenCV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake git ant pkg-config unzip wget

      - name: Build OpenCV Java
        run: bash install_opencv_java.sh

      - name: Compile Java source
        run: javac -cp .:libs/opencv-4.7.0.jar src/Main.java

      - name: Run application (headless test)
        run: |
          xvfb-run -a java -cp .:libs/opencv-4.7.0.jar -Djava.library.path=libs/native src.Main &
          sleep 10
          pkill java
        env:
          DISPLAY: :99
