name: Java CI with Webcam Capture

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package assembly:single

      - name: Test jar contents
        run: jar tf target/useless-program-1.0-SNAPSHOT-jar-with-dependencies.jar

      - name: Upload jar as GitHub Actions artifact
        uses: actions/upload-artifact@v4
        with:
          name: UselessProgram-jar
          path: target/useless-program-1.0-SNAPSHOT-jar-with-dependencies.jar

      - name: Run application from jar
        run: |
          (java -jar target/useless-program-1.0-SNAPSHOT-jar-with-dependencies.jar & P=$!; sleep 10; kill -9 $P 2>/dev/null || true)

