name: Java CI with Gradle and Webcam Capture

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Configure Git
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Bump patch version in build.gradle
        id: bump_version
        shell: bash
        run: |
          VERSION_LINE=$(grep '^version' build.gradle)
          VERSION=$(echo "$VERSION_LINE" | sed -E "s/.*['\"]([0-9]+\.[0-9]+\.[0-9]+)['\"].*/\1/")
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          sed -i.bak "s/version = '[0-9]*\.[0-9]*\.[0-9]*'/version = '$NEW_VERSION'/" build.gradle
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add build.gradle
          git commit -m "Bump version to $NEW_VERSION" || echo "No changes to commit"

      - name: Build with Gradle
        run: ./gradlew build || gradle build

      - name: Test jar contents
        run: |
          ls -lh build/libs/
          jar tf build/libs/*.jar

      - name: Run application from jar
        run: |
          (java -jar build/libs/*.jar & P=$!; sleep 10; kill -9 $P 2>/dev/null || true)

      - name: Create Release
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bump_version.outputs.new_version }}
          name: Release v${{ steps.bump_version.outputs.new_version }}
          files: build/libs/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Version Update
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        run: |
          git push
          git push --tags

